---
- hosts: security_group_webinstsg
  tasks:
- name: install the latest version of Apache
    yum:
    name: "{{ item }}"
    state: latest
    loop:
      - httpd
      - mariadb-server
- name: Copy configuration
copy:
src: /home/ec2-user/environment/ansible_kishore/httpd.conf
dest: /etc/httpd/conf/httpd.conf
notify: "restart apache"
- name: Copy code
copy:
src: /home/ec2-user/environment/ansible_kishore/index.html
dest: /var/www/html
- name: Start service httpd, if not started
service:
name: "{{ item }}"
state: started
enabled: yes
loop:
- httpd
- mariadb
handlers:
- name: restart apache
service:
name: "{{item}}"
state: restarted
loop:
- httpd
- mariadb
