- hosts: localhost
  tasks:
  - name: Ansible register variable basic example
    shell: "find *.txt"
    args:
      chdir: "/home/ec2-user/environment/var"
    register: find_output

  - debug:
      var: find_output
